apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: hello
        image: laurentiuspilca/qw-test1
        ports:
        - containerPort: 8080