apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-app-deployment
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-app
  template:
    metadata:
      labels:
        app: secret-app
    spec:
      containers:
      - name: hello
        image: laurentiuspilca/saconf2019-e3:v1
        volumeMounts:
            - name: secret-data
              mountPath: "/etc/secret-data"
              readOnly: true
        ports:
        - containerPort: 8080
      volumes:
        - name: secret-data
          secret:
            secretName: saconf2019-ex3-secret