apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
 name: mongo
spec:
 serviceName: "mongo"
 replicas: 1
 template:
  metadata:
   labels:
    role: mongo
    environment: test
 spec:
 terminationGracePeriodSeconds: 10
 volumes:
  - name: mongo-pv-storage
    persistentVolumeClaim:
     claimName: mongo-pv-claim
 containers:
  - name: mongo
    image: mongo
    command:
     - mongod
     - "--bind_ip"
     - 0.0.0.0
     - "--smallfiles"
     - "--noprealloc"
    ports:
     - containerPort: 27017
    volumeMounts:
     - name: mongo-pv-storage
       mountPath: /data/db