kind: Service
apiVersion: v1
metadata:
  name: health-check-app-deployment
spec:
  selector:
    app: health-check-app-deployment
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: LoadBalancer